"""Initial migration

Revision ID: b00e87b132ed
Revises: 
Create Date: 2024-08-30 12:46:55.050448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00e87b132ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('movies', 'original_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('movies', 'overview',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('movies', 'poster_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('movies', 'vote_count')
    op.drop_column('movies', 'backdrop_path')
    op.drop_column('movies', 'popularity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('popularity', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('backdrop_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('vote_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('movies', 'poster_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('movies', 'overview',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('movies', 'original_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('movies', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
