"""Add backdrop_path column for bg

Revision ID: ce03316f64a1
Revises: 38067d1d4f09
Create Date: 2024-09-02 12:38:29.146070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce03316f64a1'
down_revision: Union[str, None] = '38067d1d4f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('backdrop_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'backdrop_path')
    # ### end Alembic commands ###
